version: "3.5"

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: "${NEXT_PUBLIC_API_URL}"

    ports:
      - "3000:3000"
    restart: always
    networks:
      - aee_digital_backend
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

networks:
  aee_digital_backend:
    external: true